### ISSUE TITLE
Client for testing?

### ISSUE THREAD

**Issue by edysli** [uchicago/shibboleth-oidc#20]
I got that cool project to run on my IdP, but I don't have any client to test it yet. How do you guys test it? any recommendations?

**Comment by mmoayyed** [comment]
We have been testing it via: https://github.com/mmoayyed/simple-web-app

Note the fork.

**Comment by mmoayyed** [comment]
We are also going through conformance tests with openid.net, you could try there but you'd have to know your way around the config. Start with the simple webapp first.

**Comment by edysli** [comment]
I'll try that, thanks!
