### ISSUE TITLE
Couple of Default IdP Configuration notes

### ISSUE THREAD

**Issue by tomzeller** [uchicago/shibboleth-oidc#25]
- Maybe you mean -P install ?

```
mvn clean install -P new
[WARNING] The requested profile "new" could not be activated because it does not exist.
```
- I guess I need to specify M2_HOME ?

```
mvnw clean install -P new
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
```
- Is net.unicon.authn.jaas.SimpleLoginModule from https://github.com/mmoayyed/dummy-jaas-loginmodule ?

**Comment by mmoayyed** [comment]
- OK. I think I may have messed up the pom when I did a merge across branches. That command should activate a "new" profile for you. I'll get this fixed/ 
- You should, yes. 
- Yes. Purely used to mock authentication.

**Comment by mmoayyed** [comment]
No. I see the new profile in there. What is version of Maven that you use?

**Comment by mmoayyed** [comment]
Pull and try again please. The maven wrapper config was missing.
