### ISSUE TITLE
Inexact directives in installation instructions

### ISSUE THREAD

**Issue by dominique-p** [uchicago/shibboleth-oidc#35]
The installation instructions found in the file `README.md` on
https://github.com/uchicago/shibboleth-oidc#user-content-default-idp-configuration
contain a few inexact directives:

In the section `Cross Examine Changes`:
-  `target/idp.war` should be `idp-webapp-overlay/target/idp.war`
- `idp-temp/WEB-INF.xml` should be `idp-temp/WEB-INF/web.xml`
- `idp-temp/idp/login.vm` should be `idp-temp/idp/views/login.vm `
- `idp-temp/idp/intercept/attribute-release.vm` should be `idp-temp/idp/views/intercept/attribute-release.vm`
- `idp-temp/idp/system/conf/mvc-beans.xml` should be `idp-temp/idp/conf/mvc-beans.xml`

In the section `Copy Configuration`:
- instead of copying `idp-temp/idp/conf/schema-hsqldb-schema.sql`  into `$IDP_HOME/conf` one should
copy the whole directory `idp-temp/idp/conf/schema` to `$IDP_HOME/conf/` (cf. `oidc.db.schema` in `conf/oidc.properties`).

**Comment by mmoayyed** [comment]
Thank you. This is now updated.
