### ISSUE TITLE
The zoneinfo claim is not displayed by simple-web-app

### ISSUE THREAD

**Issue by dominique-p** [uchicago/shibboleth-oidc#36]
When using simple-web-app in conjunction with shibboleth-oidc the claim `zoneinfo` is not displayed:
the page `simple-web-app/user` displays the name `zone_info` but there is no value associated.
In the attribute-resolver file the value is defined as static under the name` zoneinfo` and in the logs of the IdP server the list of claims is passed with a value `Europe/Berne` for the claim `zoneinfo`:
```
2017-01-25 02:37:16,532 - DEBUG [net.shibboleth.idp.oidc.client.userinfo.ShibbolethUserInfoRepository:131] - jsessionID:571A28010BAD4DF149BB7F90CE254F2B - Final userinfo object constructed from attributes is
 {"sub":"testuser","name":"Test User","preferred_username":"testuser","given_name":"Test","family_name":"User","middle_name":null,"nickname":null,"profile":null,"picture":null,"website":null,"gender":"male","zoneinfo":"Europe/Berne","locale":"fr-FR","updated_at":null,"birthdate":null,"email":"Test.User@unige.ch","email_verified":true,"phone_number":"+41 12 345 6789","phone_number_verified":true}
```
It is also shown as `zoneinfo` in the attribute release consent page.
But it does not show on the `simple-web-app/user` page.

I did some research:

`zoneinfo` is the official OpenID Connect claim  name, cf. http://openid.net/specs/openid-connect-core-1_0.html#Claims

The name `zone_info` is used on the server in the database schema, e.g.:
```
grep zone conf/schema/hsqldb-schema.sql 
  zone_info VARCHAR(256),
```
`zone_info` is also used in the class `DefaultUserInfo` of the `library openid-connect-common-1.2.4.jar `on the server and `openid-connect-common-1.1.12.jar` on the simple-web-app client. cf. https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/master/openid-connect-common/src/main/java/org/mitre/openid/connect/model/DefaultUserInfo.java#L309

Changing the name of the column in `hsqldb-schema.sql` from `zone_info` to `zoneinfo` did not fix the problem.

- Can you reproduce it? (i.e. do you see a value associated to `zone_info` on `simple-web-app/user`?)

**Comment by mmoayyed** [comment]
Yes I can reproduce this but I think this is a bug on the same-app part that has to do with JSON parsing of the value.

**Comment by mmoayyed** [comment]
The UserInfoFetcher of the sample app does receive:

```
{"sub":"jsmith","name":"Admin","preferred_username":"MrSmith","given_name":"Jim","family_name":"Hickster","middle_name":"Ken","nickname":"TheAdmin","profile":"https://example.com/profile","picture":"https://example.com/profile/image.jpg","website":"https://example.com","gender":"Male","zoneinfo":"America/Los_Angeles","locale":"en_US","updated_at":"2800012","birthdate":"1980-07-16","email":"jsmith@somewhere.org","email_verified":true,"phone_number":"+14255551212","phone_number_verified":true,"address":{"formatted":"201 Street Name, Gilbert AZ 85258"}}
```

The bug is indicated by the red circle in the screenshot below. `userInfoString` gets everything the IdP is releasing. 

![image](https://cloud.githubusercontent.com/assets/1205228/25751338/7d3f4cd2-3169-11e7-87fa-f52481a0604d.png)

**Comment by mmoayyed** [comment]
See https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/issues/996

**Comment by mmoayyed** [comment]
I am in the process of changing/updating the sample app to more recent versions of mitre that seem to have fixed this issue.

**Comment by mmoayyed** [comment]
This is now done, and zoneinfo is showing up correctly.
