### ISSUE TITLE
IDP version / OpenSAML versions out sync in IDP 3.3.1

### ISSUE THREAD

**Issue by lhoekenga** [uchicago/shibboleth-oidc#39]
The top level pom.xml uses the IDP version number for the OpenSAML version number:
        <opensaml.version>${project.version}</opensaml.version>

The OpenSAML version number (3.3.0) was not revved with the release of IDP 3.3.1

[WARNING] The requested profile "new" could not be activated because it does not exist.
[ERROR] Failed to execute goal on project idp-webapp: Could not resolve dependencies for project net.shibboleth.idp:idp-webapp:war:3.3.1: The following artifacts could not be resolved: org.opensaml:opensaml-core:jar:3.3.1, org.opensaml:opensaml-messaging-api:jar:3.3.1, org.opensaml:opensaml-messaging-impl:jar:3.3.1, org.opensaml:opensaml-profile-api:jar:3.3.1, org.opensaml:opensaml-profile-impl:jar:3.3.1, org.opensaml:opensaml-saml-api:jar:3.3.1, org.opensaml:opensaml-saml-impl:jar:3.3.1, org.opensaml:opensaml-security-api:jar:3.3.1, org.opensaml:opensaml-security-impl:jar:3.3.1, org.opensaml:opensaml-soap-api:jar:3.3.1, org.opensaml:opensaml-soap-impl:jar:3.3.1, org.opensaml:opensaml-storage-api:jar:3.3.1, org.opensaml:opensaml-storage-impl:jar:3.3.1, org.opensaml:opensaml-xmlsec-api:jar:3.3.1, org.opensaml:opensaml-xmlsec-impl:jar:3.3.1: Could not find artifact org.opensaml:opensaml-core:jar:3.3.1 in shib-release (https://build.shibboleth.net/nexus/content/groups/public) -> [Help 1]

**Comment by mmoayyed** [comment]
Thanks for the issue report. I'll see if I can find authorized time to work on this, but if you want to submit a PR to fix the version issue that is supremely welcome.

**Comment by mmoayyed** [comment]
Fixed.
