### ISSUE TITLE
Stored procedure missing when using mysql as a backend

### ISSUE THREAD

**Issue by lhoekenga** [uchicago/shibboleth-oidc#41]
I'm trying to use the mysql as the store for OIDC.  The schema provided appears to be incorrect, (or maybe the SQL being issued by the OIDC flow is assuming that hsqldb is being used?)

from oidc.properties:
from oidc.properties:
oidc.db.schema=%{idp.home}/conf/schema/mysql-schema.sql
oidc.db.driver=com.mysql.jdbc.Driver
oidc.db.url=jdbc:mysql://mysql.example.edu:3306/oidc?autoReconnect=true
oidc.db.uid=oidc
oidc.db.psw=password

from idp-process.log:
2017-05-04 17:41:25,874 - ERROR [javax.persistence.PersistenceException:76] - xxx.xxx.xxx.xxx -
javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.0.v20150309-bf26070): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: PROCEDURE shibboleth_stage.IDENTITY does not exist
Error Code: 1305
Call: CALL IDENTITY()
Query: ValueReadQuery(name="SEQ_GEN_IDENTITY" sql="CALL IDENTITY()")
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:879)
Caused by: org.eclipse.persistence.exceptions.DatabaseException:
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: PROCEDURE shibboleth_stage.IDENTITY does not exist
Error Code: 1305
Call: CALL IDENTITY()
Query: ValueReadQuery(name="SEQ_GEN_IDENTITY" sql="CALL IDENTITY()")
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:340)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: PROCEDURE shibboleth_stage.IDENTITY does not exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

**Comment by mmoayyed** [comment]
You want to check with https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server first and see they can provide a better schema definition. 

https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/tree/master/openid-connect-server-webapp/src/main/resources/db/mysql

**Comment by mmoayyed** [comment]
Correct link for 1.2: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/tree/1.2.x/openid-connect-server-webapp/src/main/resources/db/tables

**Comment by lhoekenga** [comment]
The mysql schema available from the mitreid-connect repo is the same as the
one distributed in the shibboleth-oidc repo.

Liam

**Comment by mmoayyed** [comment]
Thanks for checking. That would be something for them to fix, I suppose.

**Comment by lhoekenga** [comment]
Actually, the problem seems to be in system/conf/oidc-protocol-storage.xml

The databasePlatform property needs to match the database backend being used, e.g.

    <bean id="jpaAdapter" class="org.springframework.orm.jpa.vendor.EclipseLinkJpaVendorAdapter">
        <property name="databasePlatform" value="org.eclipse.persistence.platform.database.MySQLPlatform" />
        <property name="showSql" value="true" />
    </bean>
