### ISSUE TITLE
Can't add new users nor test User / Admin profiles

### ISSUE THREAD

**Issue by OlivierNappert** [uchicago/shibboleth-oidc#46]
Hello !

I'm currently running the Dockerized version of your project (last version) after following all the steps in the README, everything works fine except that I don't find any ways to add a user, so that when we sign in to the OIDC Java application with his credentials it works.

Can you help me on that please ?

On this exact page, here's what happen : 

- I am prompted to Log In to test the app as a User / Admin, saying "You are Not currently Log on"
- I click on Log In and am redirected to a page with two buttons that are supposed to pre-fil a text form, by default it's "https://idptestbed/idp"
- I click on log in and am redirected to a page which request a Username and a Password, without indications about what I'm supposed to enter
- I log in, anything seems to work as long as both the username and the password are not left blank. 
- I am presented what seems an ID Token on the next page, with pre-filled informations like "Nickname : TheAdmin"
- I click on "Accept" and the next page is a 401 HTTP error, saying "State parameter error, expected null got 3f28789b52" (random number for the example)
- I'm never redirected to the main page as a logged in user

Is that normal ? Should I first register a user to log in as one ? If so, how ?

Thank you very much for your time, I hope you'll be able to help me since your project is really interesting.

Sincerely,

Olivier

**Comment by langedb** [comment]
Hi Olivier,

Shibboleth is not a comprehensive IAM solution.  It is intended to be plugged into existing authentication services such as Active Directory, LDAP, Kerberos, etc.   I recommend you start with Shibboleth in it's non-OIDC form: https://wiki.shibboleth.net/confluence/display/IDP30/Home and then once you understand how it works, move on to using this module.

**Comment by OlivierNappert** [comment]
Hi Iangedb,

Thank you for your reply. If I understand correctly, having a configured and running Kerberos server, I should be able to make them work together with adjustments in the conf files. For the Shibboleth side, do you know which files we are talking about ?

**Comment by langedb** [comment]
I've never setup Shib+Kerberos, but here's the doc: 

https://wiki.shibboleth.net/confluence/display/IDP30/SPNEGOAuthnConfiguration
