### ISSUE TITLE
Set up Checkstyle to match Idp guidelines

### ISSUE THREAD

**Issue by mmoayyed** [uchicago/shibboleth-oidc#5]
Setup Checkstyle to make sure we abide by the Idp coding practices. Fail the build if there are any violations. Do this now rather than later, so we fix stuff from the very beginning.

**Comment by mmoayyed** [comment]
This is done now. Also added NOTICE files.

**Comment by langedb** [comment]
NOTICES files need an update to get rid of Apereo
