### ISSUE TITLE
Problems running mvnw

### ISSUE THREAD

**Issue by leonchaves** [uchicago/shibboleth-oidc#56]
Hello, 

I tried running the mvnw command to build shibboleth-oidc and got the following error:

[ERROR] Failed to execute goal on project shibboleth-idp-webapp-parent: Could not resolve dependencies for project net.shibboleth.idp:shibboleth-idp-webapp-parent:pom:3.2.1: Could not find artifact net.shibboleth.idp:idp-installer:jar:3.2.1 in nexus (http://nexus.tecgraf.puc-rio.br:8081/nexus/content/groups/public) -> [Help 1]

I manually put the necessary jar files in my local repository and started to get:

[WARNING] The requested profile "new" could not be activated because
it does not exist.
[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-compiler-plugin:3.3:compile
(default-compile) on project idp-webapp-support: Compilation failure:
Compilation failure:
[ERROR]
/local/lmachado/shibboleth-oidc/idp-webapp-support/src/main/java/net/shibboleth/idp/installer/metadata/MetadataGeneratorTool.java:[23,32]
package org.opensaml.saml.common does not exist
[ERROR]
/local/lmachado/shibboleth-oidc/idp-webapp-support/src/main/java/net/shibboleth/idp/installer/metadata/MetadataGeneratorTool.java:[165,23]
cannot find symbol
[ERROR]   symbol:   class SAMLRuntimeException
[ERROR]   location: class
net.shibboleth.idp.installer.metadata.MetadataGeneratorTool

Tried with the master branch, v1.0 and branch 1. 

It seems something is wrong with your poms (that package is in opensaml-saml-api-3.3.0.jar which is in my local repository. Your pom for idp-webapp-support seems to refer to the wrong parent pom. I changed it to explicitly refer do that dependency, and it worked for this, but got another compilation error. Anyway, I shouldn't have to change your poms to make them compile). 

Thanks in advance.

Leonardo

**Comment by mmoayyed** [comment]
Thanks for the report. You're most welcome to submit a pull request to address the issue you have run into and we can further evaluate whether that fix is appropriate.
